// ============================================================
// CareerCraft AI — Document Export
// PDF via jsPDF, DOCX via docx.js
// Both support watermark for free tier
// ============================================================
import { saveAs } from 'file-saver'

const BRAND_GREEN  = [26, 61, 43]   // #1A3D2B
const BRAND_AMBER  = [232, 160, 32] // #E8A020
const TEXT_DARK    = [30, 30, 30]
const TEXT_MID     = [74, 85, 104]
const TEXT_LIGHT   = [156, 163, 175]

// ── PDF ─────────────────────────────────────────────────────
export async function downloadPDF(content, filename, toolLabel, isWatermarked = false) {
  const { jsPDF } = await import('jspdf')
  const doc  = new jsPDF({ unit: 'mm', format: 'a4' })
  const pw   = doc.internal.pageSize.getWidth()
  const ph   = doc.internal.pageSize.getHeight()
  const ml   = 22
  const mr   = pw - 22
  const mw   = mr - ml
  const lh   = 6.5

  // ── Header bar ──
  doc.setFillColor(...BRAND_GREEN)
  doc.rect(0, 0, pw, 14, 'F')
  doc.setFillColor(...BRAND_AMBER)
  doc.rect(0, 14, pw, 2, 'F')

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.setTextColor(255, 255, 255)
  doc.text('CareerCraft AI', ml, 9)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(200, 220, 210)
  doc.text(`${toolLabel}  ·  javetech.online/careercraft`, mr, 9, { align: 'right' })

  // ── Watermark ──
  if (isWatermarked) {
    doc.setFontSize(52)
    doc.setTextColor(240, 240, 240)
    doc.setFont('helvetica', 'bold')
    for (let pageNum = 1; pageNum <= 3; pageNum++) {
      if (pageNum > 1) doc.addPage()
      doc.text('CareerCraft Free', pw / 2, ph / 2, { align: 'center', angle: 45 })
    }
    doc.setPage(1)
  }

  // ── Content ──
  let y = 24
  const lines = content.split('\n')

  for (let i = 0; i < lines.length; i++) {
    const raw     = lines[i]
    const trimmed = raw.trim()

    // Page break
    if (y > ph - 22) {
      doc.addPage()
      y = 20
      if (isWatermarked) {
        doc.setFontSize(52)
        doc.setTextColor(240, 240, 240)
        doc.setFont('helvetica', 'bold')
        doc.text('CareerCraft Free', pw / 2, ph / 2, { align: 'center', angle: 45 })
      }
    }

    if (!trimmed) { y += lh * 0.5; continue }

    const isDivider  = /^[-=─]{3,}$/.test(trimmed)
    const isH1       = /^# /.test(trimmed)
    const isH2       = /^## /.test(trimmed)
    const isH3       = /^### /.test(trimmed)
    const isBold     = /^\*\*(.+)\*\*$/.test(trimmed)
    const isBullet   = /^[-•*] /.test(trimmed)
    const isNumbered = /^\d+\. /.test(trimmed)
    const isItalic   = /^\*([^*]+)\*$/.test(trimmed)

    if (isDivider) {
      doc.setDrawColor(...BRAND_AMBER)
      doc.setLineWidth(0.4)
      doc.line(ml, y, mr, y)
      y += 4; continue
    }

    const clean = trimmed
      .replace(/^#{1,3} /, '')
      .replace(/^\*\*(.+)\*\*$/, '$1')
      .replace(/^\*([^*]+)\*$/, '$1')
      .replace(/^[-•*] /, '')
      .replace(/^\d+\. /, '')
      .replace(/\*\*(.+?)\*\*/g, '$1')
      .replace(/\*(.+?)\*/g, '$1')

    let fontSize = 10
    let fontStyle = 'normal'
    let color = TEXT_DARK
    let indent = 0
    let spaceBefore = 0

    if (isH1)       { fontSize = 15; fontStyle = 'bold'; color = BRAND_GREEN; spaceBefore = 5 }
    else if (isH2)  { fontSize = 12; fontStyle = 'bold'; color = BRAND_GREEN; spaceBefore = 4 }
    else if (isH3)  { fontSize = 10.5; fontStyle = 'bold'; color = TEXT_DARK; spaceBefore = 3 }
    else if (isBold){ fontStyle = 'bold' }
    else if (isItalic) { fontStyle = 'italic'; color = TEXT_MID }
    else if (isBullet || isNumbered) { indent = 4; color = TEXT_MID }

    y += spaceBefore

    doc.setFont('helvetica', fontStyle)
    doc.setFontSize(fontSize)
    doc.setTextColor(...color)

    if (isBullet) {
      doc.setFillColor(...BRAND_AMBER)
      doc.circle(ml + 1, y - 1, 0.8, 'F')
    }

    const wrapped = doc.splitTextToSize(clean, mw - indent)
    for (const wl of wrapped) {
      if (y > ph - 22) { doc.addPage(); y = 20 }
      doc.text(wl, ml + indent, y)
      y += lh
    }
    if (isH1 || isH2) y += 1
  }

  // ── Footer on every page ──
  const total = doc.internal.getNumberOfPages()
  for (let p = 1; p <= total; p++) {
    doc.setPage(p)
    doc.setFillColor(248, 250, 248)
    doc.rect(0, ph - 10, pw, 10, 'F')
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7)
    doc.setTextColor(...TEXT_LIGHT)
    doc.text('Generated by CareerCraft AI · javetech.online/careercraft', ml, ph - 4)
    doc.text(`${p} / ${total}`, mr, ph - 4, { align: 'right' })
  }

  doc.save(`${filename}.pdf`)
}

// ── DOCX ────────────────────────────────────────────────────
export async function downloadDOCX(content, filename, toolLabel, isWatermarked = false) {
  const {
    Document, Packer, Paragraph, TextRun, HeadingLevel,
    AlignmentType, BorderStyle, TableRow, TableCell, Table,
    WidthType, ShadingType
  } = await import('docx')

  const paras = []

  // Watermark notice
  if (isWatermarked) {
    paras.push(new Paragraph({
      children: [new TextRun({
        text: '⚠ CareerCraft AI Free Plan — Upgrade at javetech.online/careercraft to remove watermark.',
        color: 'CC0000', size: 18, italics: true
      })],
      spacing: { after: 300 }
    }))
  }

  const lines = content.split('\n')

  for (const line of lines) {
    const t = line.trim()
    if (!t) { paras.push(new Paragraph({ spacing: { after: 80 } })); continue }

    const isDivider  = /^[-=─]{3,}$/.test(t)
    const isH1       = /^# /.test(t)
    const isH2       = /^## /.test(t)
    const isH3       = /^### /.test(t)
    const isBullet   = /^[-•*] /.test(t)
    const isNumbered = /^\d+\. /.test(t)
    const isBold     = /^\*\*(.+)\*\*$/.test(t)

    const clean = t
      .replace(/^#{1,3} /, '')
      .replace(/^\*\*(.+)\*\*$/, '$1')
      .replace(/^\*([^*]+)\*$/, '$1')
      .replace(/^[-•*] /, '')
      .replace(/^\d+\. /, '')

    if (isDivider) {
      paras.push(new Paragraph({
        border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: 'E8A020' } },
        spacing: { after: 120 }
      }))
      continue
    }

    if (isH1) {
      paras.push(new Paragraph({
        children: [new TextRun({ text: clean, bold: true, color: '1A3D2B', size: 32 })],
        spacing: { before: 400, after: 160 }
      }))
    } else if (isH2) {
      paras.push(new Paragraph({
        children: [new TextRun({ text: clean, bold: true, color: '1A3D2B', size: 26 })],
        spacing: { before: 320, after: 120 }
      }))
    } else if (isH3) {
      paras.push(new Paragraph({
        children: [new TextRun({ text: clean, bold: true, color: '2D5016', size: 22 })],
        spacing: { before: 200, after: 80 }
      }))
    } else if (isBullet) {
      paras.push(new Paragraph({
        bullet: { level: 0 },
        children: parseRuns(clean),
        spacing: { after: 80 }
      }))
    } else if (isNumbered) {
      paras.push(new Paragraph({
        numbering: { reference: 'cc-numbering', level: 0 },
        children: parseRuns(clean),
        spacing: { after: 80 }
      }))
    } else if (isBold) {
      paras.push(new Paragraph({
        children: [new TextRun({ text: clean, bold: true, size: 22 })],
        spacing: { after: 100 }
      }))
    } else {
      paras.push(new Paragraph({
        children: parseRuns(clean),
        spacing: { after: 100 }
      }))
    }
  }

  // Footer
  paras.push(new Paragraph({ spacing: { before: 600 } }))
  paras.push(new Paragraph({
    children: [new TextRun({
      text: `Generated by CareerCraft AI · ${toolLabel} · javetech.online/careercraft`,
      color: 'AAAAAA', size: 16, italics: true
    })],
    alignment: AlignmentType.CENTER
  }))

  const doc = new Document({
    numbering: {
      config: [{
        reference: 'cc-numbering',
        levels: [{ level: 0, format: 'decimal', text: '%1.', alignment: AlignmentType.START }]
      }]
    },
    sections: [{
      properties: { page: { margin: { top: 1440, right: 1080, bottom: 1440, left: 1080 } } },
      children: paras
    }]
  })

  const blob = await Packer.toBlob(doc)
  saveAs(blob, `${filename}.docx`)
}

function parseRuns(text) {
  const { TextRun } = require('docx')
  const parts = text.split(/(\*\*.*?\*\*|\*[^*]+\*)/g)
  return parts.map(p => {
    if (/^\*\*.*\*\*$/.test(p)) return new TextRun({ text: p.replace(/\*\*/g, ''), bold: true, size: 22 })
    if (/^\*[^*]+\*$/.test(p))  return new TextRun({ text: p.replace(/\*/g, ''), italics: true, size: 22 })
    return new TextRun({ text: p, size: 22 })
  })
}
